from flask import (
    Blueprint, g, redirect, url_for, request, render_template
)
import requests
from bs4 import BeautifulSoup
from app.db import get_db

bp = Blueprint('routes', __name__)

@bp.route("/")
def index():
    db = get_db()
    links = db.execute("SELECT id, title, url, added_at FROM links ORDER BY added_at DESC").fetchall()
    return render_template("base.html", links=links)

@bp.post("/add-article")
def add_article():
    url = request.form['url']
    print("\""+url+"\"")
    db = get_db()
    page = download_page(url)
    if page.status_code != 200:
        #If automatically downloading the page failed we can still save the url
        db.execute("INSERT INTO links (url, is_live) VALUES(?, ?)", [url, False])
    else:
        title = parse_title(page)
        #Id generated by sqlite; guaranteed non null
        row = db.execute("INSERT INTO links (url, title) VALUES(?, ?) RETURNING id", [url, title])
        id = row.fetchone()['id'] 
        db.execute("INSERT INTO pages(id, url, content) values(?, ?, ?)", [id, url, page.text])

    db.commit()
    return redirect(url_for('routes.index'))

@bp.get("/archive/<int:id>")
def archive_page(id):
        db = get_db()
        page = db.execute("SELECT content FROM pages WHERE id = ?", [id]).fetchone()
        if page is not None:
            return page['content']
        else:
            url = db.execute("SELECT url FROM links WHERE id = ?", [id]).fetchone()
            if url is None:
                abort(404)
            #Unpack url value from database row
            url = url['url']
            page = download_page(url)
            if page.status_code != 200:
                mark_bad_link(id)
                abort(404)
            title = parse_title(page)
            set_title(id, str(title))
            db.execute("INSERT INTO pages (id, url, content) VALUES(?, ?, ?)", [id, url, page.text])
            db.commit()
            return page.text
def parse_title(page):
    soup = BeautifulSoup(page.text, 'html.parser')
    title = soup.title.string
    return title
def download_page(url):
    page = requests.get(url, headers={'user-agent': 'https://github.com/carewdavid/i-read-this'})
    return page
def mark_bad_link(id):
    db = get_db()
    db.execute("UPDATE links set is_live = FALSE WHERE id = ?", [id])
    db.commit()

def set_title(id, title):
    db = get_db()
    db.execute("UPDATE links set title = ? WHERE id = ?", [title, id])
    db.commit()

